apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-web-hello
  template:
    metadata:
      labels:
        app: k8s-web-hello
    spec:
      containers:
      - name: k8s-web-hello
        image: mrpocker88/k8s-web-hello:1.0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m" ### yadroning chorak qismini ishlatishni bildiradi. Agar biz 500m qilsak yadrolarning yarmini ishlatishini bildiradi.
        ports:
        - containerPort: 3000
